#!/bin/bash

while [ true ] 
do  
  echo "--------------------------------------------------------------"; 
  date;   
  echo "----------------------------";
  echo "";
  bin/deploy; 
  echo "";  
  echo "";  
  sleep 10; 
done
